name: inkflow_pro
description: InkFlow Pro App
publish_to: 'none'

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  image_picker: ^1.0.7
  webview_flutter: ^4.7.0
  http: ^1.2.0
  in_app_purchase: ^3.1.11
  image: ^4.1.3

flutter:
  uses-material-design: true
  assets:
    - assets/3d/
